### ISSUE TITLE
How to run demo.py?

### ISSUE THREAD

**Issue by saippuakauppias** [citp/OpenWPM#136]
Hello.
I install clean ubuntu 16.04 32b on virtualbox, clone OpenWPM repo and run install.sh - this script runned without errors and warnings. But I can't run **demo.py**:

(OpenWPM2) tstsys@tstsysvb:~/OpenWPM2$ python ./demo.py
fatal: Not a git repository (or any of the parent directories): .git
TaskManager          - INFO     - 

OpenWPM Version: 0.7.0
Firefox Version: 45.6.0

========== Manager Configuration ==========
{
  "aggregator_address": [
    "127.0.0.1",
    53579
  ],
  "data_directory": "/home/tstsys/Desktop/",
  "database_name": "/home/tstsys/Desktop/crawl-data.sqlite",
  "failure_limit": null,
  "log_directory": "/home/tstsys/Desktop/",
  "log_file": "/home/tstsys/Desktop/openwpm.log",
  "logger_address": [
    "127.0.0.1",
    37480
  ],
  "num_browsers": 3,
  "screenshot_path": "/home/tstsys/Desktop/screenshots",
  "source_dump_path": "/home/tstsys/Desktop/sources",
  "testing": false
}

========== Browser Configuration ==========
Keys:
{
  "crawl_id": 0,
  "adblock-plus": 1,
  "bot_mitigation": 2,
  "browser": 3,
  "cookie_instrument": 4,
  "cp_instrument": 5,
  "debugging": 6,
  "disable_flash": 7,
  "disable_webdriver_self_id": 8,
  "donottrack": 9,
  "extension_enabled": 10,
  "ghostery": 11,
  "headless": 12,
  "http_instrument": 13,
  "https-everywhere": 14,
  "js_instrument": 15,
  "proxy": 16,
  "random_attributes": 17,
  "save_javascript": 18,
  "save_javascript_proxy": 19,
  "tp_cookies": 20,
  "tracking-protection": 21
}

  0  1      2      3        4      5      6      7      8     9      10    11     12     13    14     15     16     17     18     19     20      21
---  -----  -----  -------  -----  -----  -----  -----  ----  -----  ----  -----  -----  ----  -----  -----  -----  -----  -----  -----  ------  -----
 22  False  False  firefox  False  False  False  False  True  False  True  False  True   True  False  False  False  False  False  False  always  False
 23  False  False  firefox  False  False  False  False  True  False  True  False  False  True  False  False  False  False  False  False  always  False
 24  False  False  firefox  False  False  False  False  True  False  True  False  False  True  False  False  False  False  False  False  always  False

========== Input profile tar files ==========
  No profile tar files specified

========== Output (archive) profile directories ==========
  No profile archive directories specified

BrowserManager       - INFO     - BROWSER 22: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/tstsys/OpenWPM2/automation/BrowserManager.py", line 259, in BrowserManager
    (driver, prof_folder, browser_settings) = deploy_browser.deploy_browser(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/tstsys/OpenWPM2/automation/DeployBrowsers/deploy_browser.py", line 10, in deploy_browser
    return deploy_firefox.deploy_firefox(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/tstsys/OpenWPM2/automation/DeployBrowsers/deploy_firefox.py", line 135, in deploy_firefox
    driver = webdriver.Firefox(firefox_profile=fp, firefox_binary=fb)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 98, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

BrowserManager       - ERROR    - BROWSER 22: Spawn unsuccessful  | Proxy Ready: True  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
BrowserManager       - INFO     - BROWSER 22: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/tstsys/OpenWPM2/automation/BrowserManager.py", line 259, in BrowserManager
    (driver, prof_folder, browser_settings) = deploy_browser.deploy_browser(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/tstsys/OpenWPM2/automation/DeployBrowsers/deploy_browser.py", line 10, in deploy_browser
    return deploy_firefox.deploy_firefox(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/tstsys/OpenWPM2/automation/DeployBrowsers/deploy_firefox.py", line 135, in deploy_firefox
    driver = webdriver.Firefox(firefox_profile=fp, firefox_binary=fb)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 98, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

BrowserManager       - ERROR    - BROWSER 22: Spawn unsuccessful  | Proxy Ready: True  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
BrowserManager       - INFO     - BROWSER 22: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/tstsys/OpenWPM2/automation/BrowserManager.py", line 259, in BrowserManager
    (driver, prof_folder, browser_settings) = deploy_browser.deploy_browser(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/tstsys/OpenWPM2/automation/DeployBrowsers/deploy_browser.py", line 10, in deploy_browser
    return deploy_firefox.deploy_firefox(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/tstsys/OpenWPM2/automation/DeployBrowsers/deploy_firefox.py", line 135, in deploy_firefox
    driver = webdriver.Firefox(firefox_profile=fp, firefox_binary=fb)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 98, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

BrowserManager       - ERROR    - BROWSER 22: Spawn unsuccessful  | Proxy Ready: True  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
BrowserManager       - INFO     - BROWSER 22: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/tstsys/OpenWPM2/automation/BrowserManager.py", line 259, in BrowserManager
    (driver, prof_folder, browser_settings) = deploy_browser.deploy_browser(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/tstsys/OpenWPM2/automation/DeployBrowsers/deploy_browser.py", line 10, in deploy_browser
    return deploy_firefox.deploy_firefox(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/tstsys/OpenWPM2/automation/DeployBrowsers/deploy_firefox.py", line 135, in deploy_firefox
    driver = webdriver.Firefox(firefox_profile=fp, firefox_binary=fb)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 98, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

BrowserManager       - ERROR    - BROWSER 22: Spawn unsuccessful  | Proxy Ready: True  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
TaskManager          - CRITICAL - Browser spawn failure during TaskManager initialization, exiting...
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - TaskManager already closed

**Comment by englehardt** [comment]
The browser is not launching correctly. My hunch is that you're getting this error because you're using a 32bit Ubuntu 16.04 image. In `install.sh` we install a 64bit version of Firefox (See: https://github.com/citp/OpenWPM/blob/b6646a0d0950cdb9b0a2280ba90ce9c3e40dc915/install.sh#L39).

Would you mind to run the following from the OpenWPM root directory?
```sh
wget https://ftp.mozilla.org/pub/firefox/releases/45.6.0esr/linux-i686/en-US/firefox-45.6.0esr.tar.bz2
tar jxf firefox*.tar.bz2
rm -rf firefox-bin
mv firefox firefox-bin
rm firefox*.tar.bz2
```

If that works, I'll add a switch to the install script to detect the system architecture and install the correct version of Firefox.

**Comment by saippuakauppias** [comment]
@englehardt, yeah, it's works! Thanks!

**Comment by englehardt** [comment]
The install script should now handle this automatically. See https://github.com/citp/OpenWPM/commit/d764adc88b5f0364897c85475c35372e882bbd1f.
