### ISSUE TITLE
BrowserManager crashes when executing scan

### ISSUE THREAD

**Issue by Ni-o** [citp/OpenWPM#138]
Hi there,
I am using OpenWPM on a Project at my University for Research purposes. When I am trying to execute a scan (demo.py) I receive an error:
```
TaskManager          - INFO     -
OpenWPM Version: v0.7.0-7-g2ac606f
Firefox Version: 45.0.1
========== Manager Configuration ==========
{
  "aggregator_address": [
    "127.0.0.1",
    39358
  ],
  "data_directory": "/home/nico/Desktop/",
  "database_name": "/home/nico/Desktop/crawl-data.sqlite",
  "failure_limit": null,
  "log_directory": "/home/nico/Desktop/",
  "log_file": "/home/nico/Desktop/openwpm.log",
  "logger_address": [
    "127.0.0.1",
    37973
  ],
  "num_browsers": 3,
  "screenshot_path": "/home/nico/Desktop/screenshots",
  "source_dump_path": "/home/nico/Desktop/sources"
}

========== Browser Configuration ==========
Keys:
{
  "crawl_id": 0,
  "adblock-plus": 1,
  "bot_mitigation": 2,
  "browser": 3,
  "cookie_instrument": 4,
  "cp_instrument": 5,
  "debugging": 6,
  "disable_flash": 7,
  "donottrack": 8,
  "extension_enabled": 9,
  "ghostery": 10,
  "headless": 11,
  "https-everywhere": 12,
  "js_instrument": 13,
  "proxy": 14,
  "random_attributes": 15, 
  "save_javascript": 16,
  "tp_cookies": 17,
  "tracking-protection": 18
}

  0  1      2      3        4      5      6      7      8      9     10     11     12     13     14    15     16     17      18
---  -----  -----  -------  -----  -----  -----  -----  -----  ----  -----  -----  -----  -----  ----  -----  -----  ------  -----
  4  False  False  firefox  False  False  False  False  False  True  False  True   False  False  True  False  False  always  False
  5  False  False  firefox  False  False  False  False  False  True  False  False  False  False  True  False  False  always  False
  6  False  False  firefox  False  False  False  False  False  True  False  False  False  False  True  False  False  always  False

========== Input profile tar files ==========
  No profile tar files specified

========== Output (archive) profile directories ==========
  No profile archive directories specified


deploy_mitm_proxy    - INFO     - BROWSER 4: Intercepting Proxy listening on 45935
deploy_mitm_proxy    - INFO     - BROWSER 5: Intercepting Proxy listening on 40885
BrowserManager       - INFO     - BROWSER 5: Crash in driver, restarting browser manager
 Traceback (most recent call last):
  File "/home/nico/workspace/Pranger/automation/BrowserManager.py", line 259, in BrowserManager
    (driver, prof_folder, browser_settings) = deploy_browser.deploy_browser(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/nico/workspace/Pranger/automation/DeployBrowsers/deploy_browser.py", line 9, in deploy_browser
    return deploy_firefox.deploy_firefox(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/nico/workspace/Pranger/automation/DeployBrowsers/deploy_firefox.py", line 125, in deploy_firefox
    driver = webdriver.Firefox(firefox_profile=fp, firefox_binary=fb)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 98, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

BrowserManager       - ERROR    - BROWSER 5: Spawn unsuccessful  | Proxy Ready: True  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Laun
ched: False  | Browser Ready: False
deploy_mitm_proxy    - INFO     - BROWSER 5: Intercepting Proxy listening on 44962
BrowserManager       - INFO     - BROWSER 5: Crash in driver, restarting browser manager
 Traceback (most recent call last):
  File "/home/nico/workspace/Pranger/automation/BrowserManager.py", line 259, in BrowserManager
    (driver, prof_folder, browser_settings) = deploy_browser.deploy_browser(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/nico/workspace/Pranger/automation/DeployBrowsers/deploy_browser.py", line 9, in deploy_browser
    return deploy_firefox.deploy_firefox(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/nico/workspace/Pranger/automation/DeployBrowsers/deploy_firefox.py", line 125, in deploy_firefox
    driver = webdriver.Firefox(firefox_profile=fp, firefox_binary=fb)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 98, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.


BrowserManager       - ERROR    - BROWSER 5: Spawn unsuccessful  | Proxy Ready: True  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False
deploy_mitm_proxy    - INFO     - BROWSER 5: Intercepting Proxy listening on 54106
BrowserManager       - INFO     - BROWSER 5: Crash in driver, restarting browser manager
 Traceback (most recent call last):
  File "/home/nico/workspace/Pranger/automation/BrowserManager.py", line 259, in BrowserManager
    (driver, prof_folder, browser_settings) = deploy_browser.deploy_browser(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/nico/workspace/Pranger/automation/DeployBrowsers/deploy_browser.py", line 9, in deploy_browser
    return deploy_firefox.deploy_firefox(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/nico/workspace/Pranger/automation/DeployBrowsers/deploy_firefox.py", line 125, in deploy_firefox
    driver = webdriver.Firefox(firefox_profile=fp, firefox_binary=fb)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 98, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

BrowserManager       - ERROR    - BROWSER 5: Spawn unsuccessful  | Proxy Ready: True  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False
deploy_mitm_proxy    - INFO     - BROWSER 5: Intercepting Proxy listening on 60089
BrowserManager       - INFO     - BROWSER 5: Crash in driver, restarting browser manager
 Traceback (most recent call last):
  File "/home/nico/workspace/Pranger/automation/BrowserManager.py", line 259, in BrowserManager
    (driver, prof_folder, browser_settings) = deploy_browser.deploy_browser(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/nico/workspace/Pranger/automation/DeployBrowsers/deploy_browser.py", line 9, in deploy_browser
    return deploy_firefox.deploy_firefox(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/nico/workspace/Pranger/automation/DeployBrowsers/deploy_firefox.py", line 125, in deploy_firefox
    driver = webdriver.Firefox(firefox_profile=fp, firefox_binary=fb)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 98, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.


BrowserManager       - ERROR    - BROWSER 5: Spawn unsuccessful  | Proxy Ready: True  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False
TaskManager          - CRITICAL - Browser spawn failure during TaskManager initialization, exiting...
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - TaskManager already closed

```

Everything runs on a virtual machine (Ubuntu 16.04 64bit) on a Server. When I try to execute the same on my local PC in VirtualBox everything is fine and works well. Perhaps someone has a solution for this?

**Comment by englehardt** [comment]
Glad to hear you're using OpenWPM in your research! I suspect this is caused by running the platform in a headless environment without the headless parameter set. Try setting `browser_params[i]['headless'] = True` in demo.py [here](https://github.com/citp/OpenWPM/blob/master/demo.py#L15). By default, the demo file only runs browser 0 as headless.

This is a common cause, so if that fixes it I'll add some extra troubleshooting documentation for this issue.

**Comment by Ni-o** [comment]
Yep, that's it. :) Hope someone with the exact problem and blind as me finds this helpful.

**Comment by englehardt** [comment]
Great! I've added troubleshooting information to the README related to this: https://github.com/citp/OpenWPM/commit/344683be97b48daa82c1ada6fdf5b8f610f5d5ca.
