### ISSUE TITLE
Exception in sock.accept() causes TaskManager to hang

### ISSUE THREAD

**Issue by itdelatrisu** [citp/OpenWPM#145]
Context: Running a script that repeatedly creates a new TaskManager, loads a site, and then closes the TaskManager.  Pseudocode:
```
for url in sites:
	manager = TaskManager.TaskManager(manager_params, browser_params)
	command_sequence = CommandSequence.CommandSequence(url)
	command_sequence.get(sleep=1, timeout=120)
	manager.execute_command_sequence(command_sequence, index='**')
	manager.close()
```
Received this error infrequently (every ~12 hours), and then the program just hangs without exiting:
```
Exception in thread Thread-2905:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/.../OpenWPM/automation/SocketInterface.py", line 35, in _accept
    (client, address) = self.sock.accept()
  File "/usr/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
  File "/usr/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
```
Relevant line in `SocketInterface.py`:
```
(client, address) = self.sock.accept()
```
And when I tried catching the error, I couldn't even kill the program:
```
try:
	(client, address) = self.sock.accept()
except:
	print('sock error')  # prints successfully
	os._exit()  # program doesn't exit
```

**Comment by eriktews** [comment]
I can confirm that this still seems to happen. Do you have any idea what is happening here?

Unfortunately this is hard to reproduce.

**Comment by eriktews** [comment]
Hi, I can also confirm, this is happening with python3.

**Comment by eriktews** [comment]
@itdelatrisu Could you try to run the code from merge request #201 and see whether this still happens. When so, please post the exception here, it should now contain more information which socketserver exactly crashes and might help to debug the issue.

**Comment by eriktews** [comment]
I have one more idea, what about this line:

https://github.com/citp/OpenWPM/blob/master/automation/DataAggregator/DataAggregator.py#L27

When the connect fails with a timeout, then the 'socket' is never send here:

https://github.com/citp/OpenWPM/blob/master/automation/DataAggregator/DataAggregator.py#L35

Might this cause this behaviour?

**Comment by englehardt** [comment]
@eriktews That could definitely be the cause of the hang, since the `TaskManager` will [sit waiting](https://github.com/citp/OpenWPM/blob/8374f428c86057a96860f61be2b85c9b7142313e/automation/TaskManager.py#L287-L288) for a response.

You could try passing a timeout to the call in `TaskManager` and see if it throws an exception. See: https://docs.python.org/2/library/queue.html#Queue.Queue.get.

**Comment by eriktews** [comment]
Hi

After some debuging, I found out that it happens with loggingserver and DataAggregator as well. For DataAggregator, I could maybe attribute that to the database connect, but in loggingserver, pretty much nothing happens before the first item is added to the queue.

So currently that feels a bit like a bug in the python multiprocessing queue or something similar and I don't know how to debug that further.

@englehardt Do you still have an idea what could be happening here?
