### ISSUE TITLE
Where is run_simple_crawl.py?

### ISSUE THREAD

**Issue by Antilumo** [citp/OpenWPM#15]

**Comment by englehardt** [comment]
`run_simple_crawl.py` was replaced by the much simpler `demo.py` a few releases ago. I've updated the documentation to reflect that.

**Comment by Antilumo** [comment]
Thank you for responding and pointing this out. I have installed OpenWPM using the manual installation instructions given on your "Setting up OpenWPM" page in your wiki. I followed all instructions line by line and installed it on a clean install of ubuntu 14.04. When I run the file demo.py, I get this every time:

deploy_mitm_proxy    - INFO     - BROWSER 4: Intercepting Proxy listening on 36360
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lm/Desktop/OpenWPM/automation/BrowserManager.py", line 191, in BrowserManager
    (driver, prof_folder, browser_settings) = deploy_browser.deploy_browser(status_queue, browser_params, crash_recovery)
  File "/home/lm/Desktop/OpenWPM/automation/DeployBrowsers/deploy_browser.py", line 9, in deploy_browser
    return deploy_firefox.deploy_firefox(status_queue, browser_params, crash_recovery)
  File "/home/lm/Desktop/OpenWPM/automation/DeployBrowsers/deploy_firefox.py", line 172, in deploy_firefox
    driver = webdriver.Firefox(firefox_profile=fp, firefox_binary=fb)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 64, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 69, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 92, in _start_from_profile_path
    env=self._firefox_env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
deploy_mitm_proxy    - INFO     - BROWSER 4: Intercepting Proxy listening on 36360
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lm/Desktop/OpenWPM/automation/BrowserManager.py", line 191, in BrowserManager
    (driver, prof_folder, browser_settings) = deploy_browser.deploy_browser(status_queue, browser_params, crash_recovery)
  File "/home/lm/Desktop/OpenWPM/automation/DeployBrowsers/deploy_browser.py", line 9, in deploy_browser
    return deploy_firefox.deploy_firefox(status_queue, browser_params, crash_recovery)
  File "/home/lm/Desktop/OpenWPM/automation/DeployBrowsers/deploy_firefox.py", line 172, in deploy_firefox
    driver = webdriver.Firefox(firefox_profile=fp, firefox_binary=fb)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 64, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 69, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 92, in _start_from_profile_path
    env=self._firefox_env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


The program hangs there for a while, and eventually terminates and shows this:

BrowserManager       - ERROR    - BROWSER 4: Spawn unsuccessful | Profile: True | Display: True | Launch attempted: True | Browser: False
TaskManager          - CRITICAL - Browser spawn failure during TaskManager initialization, exiting...
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - Attempted to execute command on a closed TaskManager
TaskManager          - ERROR    - TaskManager already closed

Do you know what could be happening?

**Comment by englehardt** [comment]
The dependencies listed in the wiki were not up to date. We now include dependencies in `install.sh`. If you run this file, it should set up your machine properly. This should fix the issue you are experiencing here (where the infrastructure is unable to find the Firefox binary).
