### ISSUE TITLE
demo.py broken: WebDriverException: Message: connection refused

### ISSUE THREAD

**Issue by eriktews** [citp/OpenWPM#173]
At least in the current master version, demo.py seems to be broken. Steps to reproduce:

* Install the latest Ubuntu 16.04 Server in virtualbox (I named the default user opemwpm)
* git clone the current repository
* install.sh (I did it without flash, but I don't think this has an effect on the problem)
* python demo.py

Then you get the following output:
```
  0  1      2      3        4      5      6      7      8      9     10     11     12    13     14     15    16     17     18     19      20     21
---  -----  -----  -------  -----  -----  -----  -----  -----  ----  -----  -----  ----  -----  -----  ----  -----  -----  -----  ------  -----  -----
  1  False  False  firefox  False  False  False  False  False  True  False  True   True  False  False  {}    False  False  False  always  False  False
  2  False  False  firefox  False  False  False  False  False  True  False  False  True  False  False  {}    False  False  False  always  False  False
  3  False  False  firefox  False  False  False  False  False  True  False  False  True  False  False  {}    False  False  False  always  False  False

========== Input profile tar files ==========
  No profile tar files specified

========== Output (archive) profile dirs ==========
  No profile archive directories specified


BrowserManager       - INFO     - BROWSER 2: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/openwpm/OpenWPM/automation/BrowserManager.py", line 344, in BrowserManager
    status_queue, browser_params, manager_params, crash_recovery)
  File "/home/openwpm/OpenWPM/automation/DeployBrowsers/deploy_browser.py", line 11, in deploy_browser
    return deploy_firefox.deploy_firefox(status_queue, browser_params, manager_params, crash_recovery)
  File "/home/openwpm/OpenWPM/automation/DeployBrowsers/deploy_firefox.py", line 155, in deploy_firefox
    firefox_options=fo, log_path=interceptor.fifo)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: connection refused
```

After a while, it repeats. Playing around with python looks like the python process is trying to establish a socket connection to firefox/geckodriver, which also seems to listen on some ports. So it's currently hard to me to guess what is going wrong here.

Should you have any issues reproducing this, please let me know.

**Comment by eriktews** [comment]
Sorry, I think I found the issue by now. I accidentally started OpenWPM without a graphics environment. As a result the browser which was not configured to go to headless mode couldn't start, so the error message was generated. While I think that error reporting in this case can still be improved, it's not a real bug.
