### ISSUE TITLE
It is still possible to crash without saving the profile

### ISSUE THREAD

**Issue by englehardt** [citp/OpenWPM#33]
In commit 7bc545f11c0b879ccf1ec58d8f7970d3fda7bb36 and d2fda454523663d37e14131b960821822f2cc2dd we added support for automatic profile archiving during shutdown from child exceptions or `TaskManager` closures. Test cases of these errors are including in `tests/test_profile.py`, yet it still seems possible to end a crawl without saving the profile. See:

```
TaskManager          - INFO     - BROWSER 1: Timeout while executing command, DUMP_STORAGE_VECTORS, killing browser manager
deploy_mitm_proxy    - INFO     - BROWSER 1: Intercepting Proxy listening on 40586
BrowserManager       - INFO     - BROWSER 1: Crash in driver, restarting browser manager
 <class 'socket.error'>
 [Errno 111] Connection refused
Exception in thread Thread-6039:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/TaskManager.py", line 438, in _issue_command
    success = browser.restart_browser_manager(clear_profile = reset)
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/BrowserManager.py", line 167, in restart_browser_manager
    return self.launch_browser_manager()
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/BrowserManager.py", line 133, in launch_browser_manager
    self.logger.error("BROWSER %i: Spawn unsuccessful %s" % error_string)
TypeError: %d format: a number is required, not str

TaskManager          - INFO     - BROWSER 1: Timeout while executing command, GET, killing browser manager
TaskManager          - CRITICAL - BROWSER 1: Command execution failure pushes failure count above the allowable limit. Setting failure_flag.
CLOSING TaskManager after batch
TaskManager          - ERROR    - TaskManager already closed
Total time: 306.544947147
```
as well as:

```
2015-11-09 08:13:30,470 - MainProcess[Thread-6039] - TaskManager          - INFO    : BROWSER 1: Timeout while executing command, DUMP_STORAGE_VECTORS, killing browser manager
2015-11-09 08:13:30,471 - MainProcess[Thread-6039] - BrowserManager       - DEBUG   : BROWSER 1: Display process does not exit
2015-11-09 08:13:30,471 - MainProcess[Thread-6039] - BrowserManager       - DEBUG   : BROWSER 1: Screen lockfile already removed
2015-11-09 08:13:30,471 - MainProcess[Thread-6039] - BrowserManager       - DEBUG   : BROWSER 1: Browser process does not exist
2015-11-09 08:13:30,471 - MainProcess[Thread-6039] - BrowserManager       - DEBUG   : BROWSER 1: Spawn attempt 0
2015-11-09 08:13:30,490 - Process-415[Thread-6039] - deploy_mitm_proxy    - INFO    : BROWSER 1: Intercepting Proxy listening on 40586
2015-11-09 08:13:30,490 - Process-415[Thread-6039] - BrowserManager       - INFO    : BROWSER 1: Crash in driver, restarting browser manager
 <class 'socket.error'>
 [Errno 111] Connection refused
2015-11-09 08:17:00,694 - MainProcess[Thread-6040] - TaskManager          - INFO    : BROWSER 1: Timeout while executing command, GET, killing browser manager
2015-11-09 08:17:00,694 - MainProcess[Thread-6040] - TaskManager          - CRITICAL: BROWSER 1: Command execution failure pushes failure count above the allowable limit. Setting failure_flag.
2015-11-09 08:17:00,793 - MainProcess[MainThread] - TaskManager          - DEBUG   : TaskManager failure threshold exceeded, raising CommandExecutionError
2015-11-09 08:17:00,793 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: Joining command thread
2015-11-09 08:17:00,793 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: 0.000008 seconds to join command thread
2015-11-09 08:17:00,793 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: Killing browser manager...
2015-11-09 08:17:00,793 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: Display process does not exit
2015-11-09 08:17:00,794 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: Screen lockfile already removed
2015-11-09 08:17:00,794 - MainProcess[MainThread] - BrowserManager       - DEBUG   : BROWSER 1: Browser process does not exist
2015-11-09 08:17:00,794 - MainProcess[MainThread] - TaskManager          - DEBUG   : Telling the DataAggregator to shut down...
2015-11-09 08:17:03,825 - MainProcess[MainThread] - TaskManager          - DEBUG   : DataAggregator took 3.03015780449 seconds to close
2015-11-09 08:17:03,825 - MainProcess[MainThread] - TaskManager          - DEBUG   : Telling the LevelDBAggregator to shut down...
2015-11-09 08:17:03,825 - MainProcess[MainThread] - TaskManager          - DEBUG   : LevelDBAggregator took 9.05990600586e-06 seconds to close
```
Commit 6b4302722dae75c6be8bd0ed49409ef06173e7b5 fixes the socket bug that caused this crash. It's still unclear to me how the `TaskManager` shut down without archiving the profile.

**Comment by englehardt** [comment]
Closing, this was a non-bug. Just a mistake.
