### ISSUE TITLE
Database on disk malformed error

### ISSUE THREAD

**Issue by dreisman** [citp/OpenWPM#86]
sqlite3.DatabaseError: database disk image is malformed

This error is recoverable following these steps:

http://froebe.net/blog/2015/05/27/error-sqlite-database-is-malformed-solved/

**Comment by englehardt** [comment]
Do you know what caused this to happen? Can you post the log immediately preceding this error?

**Comment by dreisman** [comment]
deploy_mitm_proxy    - INFO     - BROWSER 5637: Intercepting Proxy listening on 40202
BrowserManager       - INFO     - BROWSER 5637: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/BrowserManager.py", line 254, in BrowserManager
    status_queue)
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/Proxy/deploy_mitm_proxy.py", line 31, in init_proxy
    m = MITMProxy.InterceptingMaster(server, proxy_site_queue, browser_params, manager_params, status_queue)
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/Proxy/MITMProxy.py", line 32, in __init__
    self.db_socket.connect(*manager_params['aggregator_address'])
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/SocketInterface.py", line 95, in connect
    self.sock.connect((host, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

BrowserManager       - ERROR    - BROWSER 5637: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: False  | Profile Tar: False  | Display: False  | Launch Attempted: False  | Br
owser Launched: False  | Browser Ready: False 
TaskManager          - CRITICAL - Browser spawn failure during TaskManager initialization, exiting...
Traceback (most recent call last):
  File "/home/ubuntu/openwpm-census/census_crawl_stateful.py", line 59, in <module>
    manager = TaskManager.TaskManager(manager_params, browser_params, process_watchdog=True)
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/TaskManager.py", line 124, in __init__
    self._launch_browsers()
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/TaskManager.py", line 177, in _launch_browsers
    self.close(post_process=False)
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/TaskManager.py", line 503, in close
    self._shutdown_manager()
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/TaskManager.py", line 298, in _shutdown_manager
    (browser.crawl_id,)))
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/SocketInterface.py", line 113, in send
    sent = self.sock.send(msg[totalsent:])
socket.error: [Errno 32] Broken pipe
!!!! Starting crawler !!!!
Traceback (most recent call last):
  File "/home/ubuntu/openwpm-census/census_crawl_stateful.py", line 59, in <module>
    manager = TaskManager.TaskManager(manager_params, browser_params, process_watchdog=True)
  File "/home/ubuntu/openwpm-census/OpenWPM/automation/TaskManager.py", line 88, in __init__
    self.db.executescript(f.read())
sqlite3.DatabaseError: database disk image is malformed

**Comment by dreisman** [comment]
The error may be due to a transient issue (sqlite bug, hardware issue). Given the error preceding DatabaseError it may have been due to a failed socket.

**Comment by englehardt** [comment]
I think it's safe to say this was a transient issue. I haven't seen this myself over the past year.
